exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('users').then(function() {
    // Inserts seed entries
    return knex('users').insert([
      {
        name: 'Cristiano Stanislaw',
        password: 'Y06IsDjc',
        email: 'cstanislaw4p@purevolume.com',
        phone: '228-372-6741',
        country: 'United States',
      },
      {
        name: 'Katinka Cody',
        password: 'BSvT6y8pXx',
        email: 'kcody4q@yellowpages.com',
        phone: '724-172-4153',
        country: 'Sweden',
      },
      {
        name: 'Mercy Desseine',
        password: 't67hUCLl',
        email: 'mdesseine4r@harvard.edu',
        phone: '436-266-4992',
        country: 'Czech Republic',
      },
      {
        name: 'Roarke Parfrey',
        password: 'Z2Sz64uOc',
        email: 'rparfrey4s@tiny.cc',
        phone: '697-562-3400',
        country: 'Uzbekistan',
      },
      {
        name: 'Mychal Catherine',
        password: 'UZc4x3S6kJ9K',
        email: 'mcatherine4t@paginegialle.it',
        phone: '694-441-1795',
        country: 'Russia',
      },
      {
        name: 'Kendrick Roskam',
        password: 'nuS2PV',
        email: 'kroskam4u@marketwatch.com',
        phone: '423-256-3011',
        country: 'Russia',
      },
      {
        name: 'Lelia Leyborne',
        password: 'Z5LVy1a',
        email: 'lleyborne4v@goodreads.com',
        phone: '226-209-6591',
        country: 'China',
      },
      {
        name: 'Jeff Willishire',
        password: 'i2rHrqpeCg',
        email: 'jwillishire4w@privacy.gov.au',
        phone: '310-469-3957',
        country: 'Indonesia',
      },
      {
        name: "Marty D'Onise",
        password: 'f3LKj0zDU9R',
        email: 'mdonise4x@reddit.com',
        phone: '121-651-0525',
        country: 'Finland',
      },
      {
        name: 'Sonny Pengelly',
        password: 'M2z1XPuFhIl',
        email: 'spengelly4y@webeden.co.uk',
        phone: '214-213-8214',
        country: 'United States',
      },
      {
        name: 'Jemmie Girvin',
        password: '0Y5UO52m',
        email: 'jgirvin4z@lulu.com',
        phone: '510-849-4506',
        country: 'Yemen',
      },
      {
        name: 'Thedric Cund',
        password: 'VLCpvbbm3s',
        email: 'tcund50@theguardian.com',
        phone: '318-214-6873',
        country: 'United States',
      },
      {
        name: 'Ber Loughton',
        password: 'XlhJKU',
        email: 'bloughton51@toplist.cz',
        phone: '952-443-9680',
        country: 'Indonesia',
      },
      {
        name: 'Solomon Asman',
        password: 'f6mahA',
        email: 'sasman52@flickr.com',
        phone: '706-164-0523',
        country: 'Sweden',
      },
      {
        name: 'Natty Pardoe',
        password: 'PgBnmD3r4',
        email: 'npardoe53@google.it',
        phone: '681-853-4441',
        country: 'Sweden',
      },
      {
        name: 'Brook Koeppe',
        password: '3lgoEr8xSlpn',
        email: 'bkoeppe54@engadget.com',
        phone: '982-215-6449',
        country: 'China',
      },
      {
        name: 'Jorry Crean',
        password: 'DoFBjxplL92',
        email: 'jcrean55@theglobeandmail.com',
        phone: '534-586-1299',
        country: 'Japan',
      },
      {
        name: 'Bartlett Claige',
        password: 'IrUDZY3Lxg',
        email: 'bclaige56@goo.ne.jp',
        phone: '268-770-0122',
        country: 'Costa Rica',
      },
      {
        name: 'Thain Pauling',
        password: 'agTia3',
        email: 'tpauling57@eepurl.com',
        phone: '329-842-9467',
        country: 'Indonesia',
      },
      {
        name: 'Tatiana Sunter',
        password: 'iIIcqH',
        email: 'tsunter58@nymag.com',
        phone: '959-933-6991',
        country: 'Venezuela',
      },
      {
        name: 'Berthe Binch',
        password: 'MVBEh4Uu',
        email: 'bbinch59@lycos.com',
        phone: '207-750-1527',
        country: 'Poland',
      },
      {
        name: 'Kliment Folli',
        password: 'KuQWaN',
        email: 'kfolli5a@usa.gov',
        phone: '232-369-1715',
        country: 'Ukraine',
      },
      {
        name: 'Shannon Laydel',
        password: 'I5iYOyom',
        email: 'slaydel5b@sun.com',
        phone: '416-274-1330',
        country: 'Philippines',
      },
      {
        name: 'Osbourn Propper',
        password: 'eymduspA',
        email: 'opropper5c@blogs.com',
        phone: '775-256-2059',
        country: 'Guatemala',
      },
      {
        name: 'Nixie Peschmann',
        password: '1XKTM14odxQ',
        email: 'npeschmann5d@mail.ru',
        phone: '749-902-7619',
        country: 'Spain',
      },
      {
        name: 'Dori Petersen',
        password: 'HKz2B8X3k',
        email: 'dpetersen5e@ebay.co.uk',
        phone: '226-773-2912',
        country: 'Egypt',
      },
      {
        name: 'Damien Gurko',
        password: '3IcF9dYG',
        email: 'dgurko5f@dmoz.org',
        phone: '619-977-1103',
        country: 'Morocco',
      },
      {
        name: 'Faydra Linsay',
        password: 'XI51EHUr2D',
        email: 'flinsay5g@bloomberg.com',
        phone: '365-631-3938',
        country: 'Greece',
      },
      {
        name: 'Elsinore Gommowe',
        password: 'IkhtdJk',
        email: 'egommowe5h@behance.net',
        phone: '197-887-1890',
        country: 'Indonesia',
      },
      {
        name: 'Rae Maccraw',
        password: 'WCL5tp3Fr',
        email: 'rmaccraw5i@merriam-webster.com',
        phone: '123-392-6547',
        country: 'China',
      },
      {
        name: 'Yank Flohard',
        password: '57K09e',
        email: 'yflohard5j@dot.gov',
        phone: '132-909-3466',
        country: 'Albania',
      },
      {
        name: 'Nelie Gresly',
        password: 'KOjG17Ghzu',
        email: 'ngresly5k@elpais.com',
        phone: '353-362-2949',
        country: 'China',
      },
      {
        name: 'Humfrid Grafton-Herbert',
        password: '9hnNcc',
        email: 'hgraftonherbert5l@google.fr',
        phone: '986-678-3669',
        country: 'Peru',
      },
      {
        name: 'Noah Melross',
        password: 'SH1wOznfmb2',
        email: 'nmelross5m@hatena.ne.jp',
        phone: '592-621-9645',
        country: 'Indonesia',
      },
      {
        name: 'Hyman Provis',
        password: 'fp7yOU',
        email: 'hprovis5n@uol.com.br',
        phone: '672-754-9265',
        country: 'Poland',
      },
      {
        name: 'Brnaby Mastrantone',
        password: 'IT6uQkp',
        email: 'bmastrantone5o@answers.com',
        phone: '451-637-1704',
        country: 'Philippines',
      },
      {
        name: 'Maryanne Clacey',
        password: 'Nsfm1w',
        email: 'mclacey5p@alexa.com',
        phone: '842-817-7817',
        country: 'Portugal',
      },
      {
        name: 'Bennie Preskett',
        password: 'MXyGxz3oN6Kz',
        email: 'bpreskett5q@csmonitor.com',
        phone: '678-776-3984',
        country: 'Lebanon',
      },
      {
        name: 'Lilah Fould',
        password: 'vDZnos9ngf',
        email: 'lfould5r@latimes.com',
        phone: '157-222-1896',
        country: 'Morocco',
      },
      {
        name: 'Norris Dunsford',
        password: 'kH1fJNe',
        email: 'ndunsford5s@ucoz.com',
        phone: '535-323-7451',
        country: 'Sweden',
      },
      {
        name: 'Ladonna Cone',
        password: 'DDQ0HN2NT8',
        email: 'lcone5t@cnbc.com',
        phone: '774-641-3361',
        country: 'Poland',
      },
      {
        name: 'Diana Rance',
        password: 'rn9VsruBKd',
        email: 'drance5u@uol.com.br',
        phone: '898-272-2124',
        country: 'Mexico',
      },
      {
        name: 'Alyss Vasyukhnov',
        password: '1rR4NVW',
        email: 'avasyukhnov5v@sogou.com',
        phone: '455-567-1866',
        country: 'China',
      },
      {
        name: 'Maxie Longmuir',
        password: 'sf3AXa0',
        email: 'mlongmuir5w@github.com',
        phone: '990-984-3827',
        country: 'China',
      },
      {
        name: 'Wildon Harner',
        password: 'UbEXNRyvMtS',
        email: 'wharner5x@ebay.com',
        phone: '823-740-2422',
        country: 'Russia',
      },
      {
        name: 'Aguistin Urch',
        password: 'DkTlyUzOC',
        email: 'aurch5y@usatoday.com',
        phone: '902-226-6516',
        country: 'Mali',
      },
      {
        name: 'Lorinda Liddle',
        password: '7kgEqnLDlM9',
        email: 'lliddle5z@free.fr',
        phone: '501-624-3169',
        country: 'Greece',
      },
      {
        name: 'Letty Ethersey',
        password: 'CQhAA0YWRX7j',
        email: 'lethersey60@usatoday.com',
        phone: '834-153-7320',
        country: 'Ukraine',
      },
      {
        name: 'Belia Kidder',
        password: '8jeTqzRe',
        email: 'bkidder61@huffingtonpost.com',
        phone: '604-948-3528',
        country: 'Portugal',
      },
      {
        name: 'Haydon Ende',
        password: '4vJALS',
        email: 'hende62@thetimes.co.uk',
        phone: '977-874-1492',
        country: 'China',
      },
      {
        name: 'Cissiee Reuben',
        password: 'GEyjD9BKLK',
        email: 'creuben63@admin.ch',
        phone: '231-916-1280',
        country: 'Russia',
      },
      {
        name: 'Frasco Blasdale',
        password: 'aPOTNQ',
        email: 'fblasdale64@shutterfly.com',
        phone: '714-429-6202',
        country: 'Ukraine',
      },
      {
        name: 'Clayton Howgate',
        password: '9QcBR3tA',
        email: 'chowgate65@yelp.com',
        phone: '983-700-2465',
        country: 'Uruguay',
      },
      {
        name: 'Wood Cyphus',
        password: 'FF2GZ5U9uOV',
        email: 'wcyphus66@vimeo.com',
        phone: '135-320-7156',
        country: 'Thailand',
      },
      {
        name: 'Danny Cowely',
        password: 'LcXFol',
        email: 'dcowely67@prweb.com',
        phone: '644-629-6971',
        country: 'China',
      },
      {
        name: 'Theresina Burnyate',
        password: '4xrruIZwCC2g',
        email: 'tburnyate68@europa.eu',
        phone: '977-917-3298',
        country: 'South Africa',
      },
      {
        name: 'Katlin Gheeorghie',
        password: 'rJX1tzhE',
        email: 'kgheeorghie69@msu.edu',
        phone: '764-122-1075',
        country: 'Ireland',
      },
      {
        name: 'Mala Tritten',
        password: 'rXxOCY',
        email: 'mtritten6a@behance.net',
        phone: '743-616-2048',
        country: 'Finland',
      },
      {
        name: 'Jonas Feighney',
        password: 'sfOKkqg',
        email: 'jfeighney6b@usatoday.com',
        phone: '628-694-0199',
        country: 'Russia',
      },
      {
        name: 'Cooper Staniforth',
        password: 'zIoeTch',
        email: 'cstaniforth6c@china.com.cn',
        phone: '874-389-6160',
        country: 'Philippines',
      },
      {
        name: 'Carolee Diamant',
        password: 'PBT7aGG8Cf9n',
        email: 'cdiamant6d@wsj.com',
        phone: '296-201-4517',
        country: 'Botswana',
      },
      {
        name: 'Joel Jeannenet',
        password: 'VdR84c',
        email: 'jjeannenet6e@discuz.net',
        phone: '870-436-8964',
        country: 'Colombia',
      },
      {
        name: 'Marabel Daunay',
        password: 'qEsZ4UlhDu0K',
        email: 'mdaunay6f@hibu.com',
        phone: '883-518-1493',
        country: 'China',
      },
      {
        name: 'Faustina Bett',
        password: 'ojWzymUMb7V',
        email: 'fbett6g@macromedia.com',
        phone: '164-397-5217',
        country: 'Venezuela',
      },
      {
        name: 'Mariel Fretwell',
        password: 'IRhqwmq',
        email: 'mfretwell6h@sohu.com',
        phone: '718-270-7471',
        country: 'United Kingdom',
      },
      {
        name: 'Cosetta Ordish',
        password: '7AOUs9KDxzT',
        email: 'cordish6i@ucsd.edu',
        phone: '138-934-3942',
        country: 'Guatemala',
      },
      {
        name: 'Evan Royal',
        password: 'GkY2YoBHzazw',
        email: 'eroyal6j@wordpress.com',
        phone: '483-207-7105',
        country: 'Indonesia',
      },
      {
        name: 'Sara-ann Kornes',
        password: 'oYm1Owq',
        email: 'skornes6k@loc.gov',
        phone: '790-251-7093',
        country: 'Indonesia',
      },
      {
        name: 'Aubrette Livett',
        password: 'kBj7Zf',
        email: 'alivett6l@github.com',
        phone: '701-785-9845',
        country: 'Russia',
      },
      {
        name: 'Christal Kinset',
        password: 'tRCMtP9hVu7P',
        email: 'ckinset6m@printfriendly.com',
        phone: '446-776-2453',
        country: 'China',
      },
      {
        name: 'Nilson Brisson',
        password: 'L6geLvdQfH',
        email: 'nbrisson6n@blogs.com',
        phone: '597-547-1379',
        country: 'China',
      },
      {
        name: 'Aloin Lockart',
        password: 'sJqF1X5',
        email: 'alockart6o@spiegel.de',
        phone: '136-835-6944',
        country: 'Ireland',
      },
      {
        name: 'Zackariah Cowpland',
        password: 'dTxD3MffgC',
        email: 'zcowpland6p@dmoz.org',
        phone: '917-283-5050',
        country: 'Ukraine',
      },
      {
        name: 'Willis Tschirschky',
        password: 'XzuNEEx4DQ4q',
        email: 'wtschirschky6q@businesswire.com',
        phone: '454-848-9932',
        country: 'China',
      },
      {
        name: 'Olivie Swiffen',
        password: 'MwzIovgAayx',
        email: 'oswiffen6r@auda.org.au',
        phone: '307-510-9169',
        country: 'Vanuatu',
      },
      {
        name: 'Fulvia Bicker',
        password: 'BdeTopA',
        email: 'fbicker6s@elpais.com',
        phone: '879-190-0263',
        country: 'China',
      },
      {
        name: 'Elden Zannini',
        password: 'EuoSv0kE',
        email: 'ezannini6t@diigo.com',
        phone: '161-999-8350',
        country: 'China',
      },
      {
        name: 'Chance Shearman',
        password: 'Pin9eX',
        email: 'cshearman6u@bloglovin.com',
        phone: '281-819-2853',
        country: 'United States',
      },
      {
        name: 'Giavani Union',
        password: 'UzpcmKtGtrpS',
        email: 'gunion6v@tumblr.com',
        phone: '266-187-3666',
        country: 'China',
      },
      {
        name: 'Gilli Digle',
        password: 'Df6H3SoV1',
        email: 'gdigle6w@miitbeian.gov.cn',
        phone: '952-254-3528',
        country: 'China',
      },
      {
        name: 'Paolo Marshman',
        password: 'j1aRPVe',
        email: 'pmarshman6x@miitbeian.gov.cn',
        phone: '245-819-7503',
        country: 'Russia',
      },
      {
        name: 'Gilberte Remmer',
        password: 'FNUrNmM3',
        email: 'gremmer6y@reference.com',
        phone: '598-903-3185',
        country: 'Russia',
      },
      {
        name: 'Tootsie Corstan',
        password: '7zLiBieg',
        email: 'tcorstan6z@barnesandnoble.com',
        phone: '573-341-3967',
        country: 'United States',
      },
      {
        name: 'Vale Mattiussi',
        password: 'P43Adt8cZ6N',
        email: 'vmattiussi70@google.es',
        phone: '535-510-7818',
        country: 'France',
      },
      {
        name: 'Wyn Fouch',
        password: '0EwvtuA8Hvos',
        email: 'wfouch71@chronoengine.com',
        phone: '214-476-2376',
        country: 'United States',
      },
      {
        name: 'Therese Lucock',
        password: 'Ye9I09yxA',
        email: 'tlucock72@hubpages.com',
        phone: '140-617-2597',
        country: 'China',
      },
      {
        name: 'Rutledge Sallarie',
        password: 'JW30SCWLRoeC',
        email: 'rsallarie73@tripadvisor.com',
        phone: '664-271-2929',
        country: 'Indonesia',
      },
      {
        name: 'Kirsti Arnaldo',
        password: '9Vk2A3RZ0vY',
        email: 'karnaldo74@ask.com',
        phone: '581-131-2486',
        country: 'China',
      },
      {
        name: 'Madalyn Feeney',
        password: 'V6CNFYU',
        email: 'mfeeney75@aboutads.info',
        phone: '425-699-3498',
        country: 'Poland',
      },
      {
        name: 'Lorelei Daveren',
        password: 'WKftow7U',
        email: 'ldaveren76@tamu.edu',
        phone: '253-191-1169',
        country: 'Russia',
      },
      {
        name: 'Hedwig Osgar',
        password: 'PSzRrzLS',
        email: 'hosgar77@chronoengine.com',
        phone: '407-117-7483',
        country: 'Poland',
      },
      {
        name: 'Jonathon Gennerich',
        password: 'ay6h6Te',
        email: 'jgennerich78@princeton.edu',
        phone: '879-200-3354',
        country: 'Vietnam',
      },
      {
        name: 'Alyse Charters',
        password: 'O0sWKEZY5sA',
        email: 'acharters79@apple.com',
        phone: '336-826-2649',
        country: 'China',
      },
      {
        name: 'Maggee Plumb',
        password: 'EygxQra821wx',
        email: 'mplumb7a@cisco.com',
        phone: '600-669-4610',
        country: 'Philippines',
      },
      {
        name: 'Dunstan Kuzma',
        password: 'blo5Ty',
        email: 'dkuzma7b@prweb.com',
        phone: '601-979-7326',
        country: 'United States',
      },
      {
        name: 'Chrotoem Bothen',
        password: 'hb7CObtj',
        email: 'cbothen7c@soundcloud.com',
        phone: '238-639-0429',
        country: 'Poland',
      },
      {
        name: 'Tanhya Ranscome',
        password: 'X1Ye2oBg',
        email: 'transcome7d@intel.com',
        phone: '103-594-5776',
        country: 'Syria',
      },
      {
        name: 'Pembroke Fredson',
        password: 'YhEkDeVB0b3',
        email: 'pfredson7e@amazonaws.com',
        phone: '713-118-9496',
        country: 'Russia',
      },
      {
        name: 'Shaylah Covolini',
        password: '9FxDdbAdDPE',
        email: 'scovolini7f@time.com',
        phone: '642-363-3336',
        country: 'Russia',
      },
      {
        name: 'Warner Finney',
        password: '4SKgwf',
        email: 'wfinney7g@bandcamp.com',
        phone: '981-628-4710',
        country: 'Sierra Leone',
      },
      {
        name: 'Rory Oliphant',
        password: 'CBQOxW',
        email: 'roliphant7h@godaddy.com',
        phone: '229-540-3008',
        country: 'Haiti',
      },
      {
        name: 'Bentley Friskey',
        password: 'gYOWdUFE3OC',
        email: 'bfriskey7i@simplemachines.org',
        phone: '688-268-3753',
        country: 'Colombia',
      },
      {
        name: 'Anneliese Albion',
        password: 'bVIYj3NNtt2D',
        email: 'aalbion7j@hp.com',
        phone: '312-244-1124',
        country: 'Indonesia',
      },
      {
        name: 'Cam Guinn',
        password: 'QliAo1TesiZ',
        email: 'cguinn7k@census.gov',
        phone: '208-283-0387',
        country: 'Egypt',
      },
      {
        name: 'Lauree McMillan',
        password: 'w7J0y0g453Gs',
        email: 'lmcmillan7l@howstuffworks.com',
        phone: '144-677-9560',
        country: 'Russia',
      },
      {
        name: 'Kristy Soanes',
        password: 'zNC8bOs7b919',
        email: 'ksoanes7m@tinyurl.com',
        phone: '283-270-2139',
        country: 'Cambodia',
      },
      {
        name: 'Benedikta Skitt',
        password: 'QYyb2Ql',
        email: 'bskitt7n@geocities.com',
        phone: '454-397-0817',
        country: 'Botswana',
      },
      {
        name: 'Colas Amorts',
        password: 'BCATpOFPXfa',
        email: 'camorts7o@usda.gov',
        phone: '359-363-8249',
        country: 'Philippines',
      },
      {
        name: 'Marianna Janczewski',
        password: 'UuyOQMv',
        email: 'mjanczewski7p@aol.com',
        phone: '841-321-7638',
        country: 'Philippines',
      },
      {
        name: 'Barde Meekin',
        password: 'FOR4iWcJ',
        email: 'bmeekin7q@slideshare.net',
        phone: '156-859-5511',
        country: 'Czech Republic',
      },
      {
        name: 'Jecho Littlemore',
        password: 'P3FDU0JGG',
        email: 'jlittlemore7r@discovery.com',
        phone: '716-391-5312',
        country: 'United States',
      },
      {
        name: 'Mathilde de Quesne',
        password: 'AbS40PyA',
        email: 'mde7s@wp.com',
        phone: '120-222-3020',
        country: 'Indonesia',
      },
      {
        name: 'Etheline Challender',
        password: 'fXrMPXe7',
        email: 'echallender7t@surveymonkey.com',
        phone: '396-978-5762',
        country: 'Philippines',
      },
      {
        name: 'Muire Payze',
        password: '29Mm1XULDw',
        email: 'mpayze7u@networkadvertising.org',
        phone: '720-443-9637',
        country: 'Indonesia',
      },
      {
        name: 'Austin Howett',
        password: 'heen71Op',
        email: 'ahowett7v@purevolume.com',
        phone: '401-159-4732',
        country: 'Ukraine',
      },
      {
        name: 'Gilli Paslow',
        password: 'MLsrgbavjRls',
        email: 'gpaslow7w@hexun.com',
        phone: '977-346-9892',
        country: 'Mexico',
      },
      {
        name: 'Trenton Bigland',
        password: 'fvmF5qh5Tpw',
        email: 'tbigland7x@storify.com',
        phone: '407-830-7885',
        country: 'Sweden',
      },
      {
        name: 'Cullen Spears',
        password: 'AC4ormbCZrKb',
        email: 'cspears7y@forbes.com',
        phone: '461-626-8103',
        country: 'Poland',
      },
      {
        name: 'Sarge Divver',
        password: 'eYVu7LRU0ch',
        email: 'sdivver7z@europa.eu',
        phone: '412-208-3152',
        country: 'United States',
      },
      {
        name: 'Gisella Brafferton',
        password: 'YiNMP8vOq89',
        email: 'gbrafferton80@pagesperso-orange.fr',
        phone: '595-458-5861',
        country: 'Indonesia',
      },
      {
        name: 'Ashlan Yeats',
        password: 't3rhCBYc',
        email: 'ayeats81@newsvine.com',
        phone: '749-721-2908',
        country: 'Bangladesh',
      },
      {
        name: 'Neron Stoyell',
        password: '0ZPJo6U',
        email: 'nstoyell82@si.edu',
        phone: '420-882-0500',
        country: 'China',
      },
      {
        name: 'Murry Manger',
        password: 'bqBHHQRz',
        email: 'mmanger83@people.com.cn',
        phone: '222-457-5000',
        country: 'Sweden',
      },
      {
        name: 'Lilias Neil',
        password: 'QeiuFo',
        email: 'lneil84@360.cn',
        phone: '764-931-0858',
        country: 'Nicaragua',
      },
      {
        name: 'Kathe Antoniat',
        password: 'pBCSKcrZh',
        email: 'kantoniat85@woothemes.com',
        phone: '869-221-0419',
        country: 'Lithuania',
      },
      {
        name: 'Adrian Horribine',
        password: 'wIRIFV9q',
        email: 'ahorribine86@nymag.com',
        phone: '750-603-7865',
        country: 'Central African Republic',
      },
      {
        name: 'Kass Bonhome',
        password: 'NBmE3GB',
        email: 'kbonhome87@goo.gl',
        phone: '851-900-5590',
        country: 'Haiti',
      },
      {
        name: 'Jeramey Rubens',
        password: 'yqCaSBAN',
        email: 'jrubens88@harvard.edu',
        phone: '723-422-2712',
        country: 'China',
      },
      {
        name: 'Lyndsay Abbatucci',
        password: 'NG6UiU',
        email: 'labbatucci89@techcrunch.com',
        phone: '693-607-9116',
        country: 'Russia',
      },
      {
        name: 'Arvy Fleetwood',
        password: '5HVCcEh',
        email: 'afleetwood8a@gravatar.com',
        phone: '531-299-2122',
        country: 'Egypt',
      },
      {
        name: 'Gannon Itzakson',
        password: 'OQ3YVyQerD66',
        email: 'gitzakson8b@posterous.com',
        phone: '351-147-7551',
        country: 'Russia',
      },
      {
        name: 'Siward Lettice',
        password: 'l46IfAthDMw',
        email: 'slettice8c@imdb.com',
        phone: '500-347-2078',
        country: 'Israel',
      },
      {
        name: 'Elspeth Eite',
        password: '9uENaLs5pbpP',
        email: 'eeite8d@independent.co.uk',
        phone: '318-458-9018',
        country: 'China',
      },
      {
        name: 'Bone Parysiak',
        password: '4Y0eeZKQgQ',
        email: 'bparysiak8e@reverbnation.com',
        phone: '763-477-4272',
        country: 'Mexico',
      },
      {
        name: 'Claretta McKevany',
        password: '33aCTa3',
        email: 'cmckevany8f@ustream.tv',
        phone: '209-166-4078',
        country: 'United States',
      },
      {
        name: 'Esteban Bardwall',
        password: 'DuxQ32Mbv',
        email: 'ebardwall8g@tamu.edu',
        phone: '268-128-2218',
        country: 'Brazil',
      },
      {
        name: 'Gabbey Durran',
        password: 'EWzpsPEKC',
        email: 'gdurran8h@altervista.org',
        phone: '599-510-2311',
        country: 'Faroe Islands',
      },
      {
        name: 'Corena Duckworth',
        password: 'pkZ1ILYuCx4',
        email: 'cduckworth8i@i2i.jp',
        phone: '761-703-8314',
        country: 'Aruba',
      },
      {
        name: 'Inglebert Isac',
        password: 'lnAa3TMFpWgX',
        email: 'iisac8j@ustream.tv',
        phone: '746-178-4560',
        country: 'Indonesia',
      },
      {
        name: 'Rosaline Dales',
        password: 'BuTa4KQwRl',
        email: 'rdales8k@census.gov',
        phone: '648-502-4164',
        country: 'China',
      },
      {
        name: 'Erminie Pierson',
        password: 'HGeVsnwbn',
        email: 'epierson8l@dot.gov',
        phone: '282-493-1760',
        country: 'China',
      },
      {
        name: 'Arvy Chatwin',
        password: 'fLnZbEK',
        email: 'achatwin8m@accuweather.com',
        phone: '508-953-2286',
        country: 'Philippines',
      },
      {
        name: 'Orton Stedman',
        password: '6QII6Ba',
        email: 'ostedman8n@shinystat.com',
        phone: '466-994-5602',
        country: 'China',
      },
      {
        name: 'Bond Biset',
        password: 'Db0KaE',
        email: 'bbiset8o@ebay.co.uk',
        phone: '844-114-7003',
        country: 'China',
      },
      {
        name: 'Lynnette Ling',
        password: '0AyLhfg2xRNM',
        email: 'lling8p@cisco.com',
        phone: '112-888-5077',
        country: 'China',
      },
      {
        name: 'Tait Edes',
        password: '6mJqunMfha',
        email: 'tedes8q@topsy.com',
        phone: '885-664-0105',
        country: 'Thailand',
      },
      {
        name: 'Veradis Streetley',
        password: 'rkbpqh8VgK',
        email: 'vstreetley8r@posterous.com',
        phone: '542-373-2059',
        country: 'Kyrgyzstan',
      },
      {
        name: 'Gloria Peasgood',
        password: 'k1biiZJZhOqm',
        email: 'gpeasgood8s@etsy.com',
        phone: '124-194-1852',
        country: 'Indonesia',
      },
      {
        name: 'Wynn Duckham',
        password: 'pyIg2HYtnO',
        email: 'wduckham8t@netvibes.com',
        phone: '779-507-4841',
        country: 'Peru',
      },
      {
        name: 'Winn McGirl',
        password: 'GIdypEaT',
        email: 'wmcgirl8u@furl.net',
        phone: '178-971-9670',
        country: 'China',
      },
      {
        name: 'Helga Kennifick',
        password: 'cFn5QTS1a9',
        email: 'hkennifick8v@nationalgeographic.com',
        phone: '578-831-9241',
        country: 'Indonesia',
      },
      {
        name: 'Emlen Rosbrough',
        password: 'BICBhUP',
        email: 'erosbrough8w@cbsnews.com',
        phone: '438-622-7187',
        country: 'Costa Rica',
      },
      {
        name: 'Spike Aujouanet',
        password: 'HSu5Ocl8LIO',
        email: 'saujouanet8x@cbsnews.com',
        phone: '461-277-1537',
        country: 'Bulgaria',
      },
      {
        name: 'Deck Mingaud',
        password: '6H3mt3s2eLC',
        email: 'dmingaud8y@pagesperso-orange.fr',
        phone: '991-925-6478',
        country: 'Norway',
      },
      {
        name: 'Amalle McInteer',
        password: 'dLUxwb0gZmi7',
        email: 'amcinteer8z@gravatar.com',
        phone: '795-225-1496',
        country: 'Czech Republic',
      },
      {
        name: 'Vinita Howcroft',
        password: 'uw4FTJeUR',
        email: 'vhowcroft90@wp.com',
        phone: '963-350-3889',
        country: 'Czech Republic',
      },
      {
        name: 'Malynda Soame',
        password: '5IIcz7',
        email: 'msoame91@de.vu',
        phone: '164-606-9898',
        country: 'Indonesia',
      },
      {
        name: 'Benedetto Dreier',
        password: 'bViQeD',
        email: 'bdreier92@istockphoto.com',
        phone: '551-409-5091',
        country: 'United Kingdom',
      },
      {
        name: 'Howey Pitsall',
        password: 'ILgeuRg',
        email: 'hpitsall93@nsw.gov.au',
        phone: '136-141-0519',
        country: 'Philippines',
      },
      {
        name: 'Stace Jellico',
        password: '0aAFCTxe',
        email: 'sjellico94@sohu.com',
        phone: '474-486-9030',
        country: 'Philippines',
      },
      {
        name: 'Orville Hartburn',
        password: 'FlTfEd6NTN',
        email: 'ohartburn95@sohu.com',
        phone: '589-581-8753',
        country: 'Vietnam',
      },
      {
        name: 'Pasquale Silkston',
        password: 'vpqSsu19',
        email: 'psilkston96@symantec.com',
        phone: '794-659-6093',
        country: 'South Korea',
      },
      {
        name: 'Larine Lygo',
        password: 'qIrH1q3kW3',
        email: 'llygo97@google.cn',
        phone: '277-476-3442',
        country: 'China',
      },
      {
        name: 'Michaela Gabbatt',
        password: 'BANRd6U02',
        email: 'mgabbatt98@blogger.com',
        phone: '349-882-7542',
        country: 'Greece',
      },
      {
        name: 'Regen Brecon',
        password: 'XsGzU5aMLO',
        email: 'rbrecon99@drupal.org',
        phone: '388-878-5967',
        country: 'China',
      },
      {
        name: 'Lewiss Sailor',
        password: 'Z2hruoovH4',
        email: 'lsailor9a@nifty.com',
        phone: '118-149-0964',
        country: 'Peru',
      },
      {
        name: 'Loella Geelan',
        password: 'llsO4hobASk',
        email: 'lgeelan9b@latimes.com',
        phone: '151-268-7278',
        country: 'Kazakhstan',
      },
    ]);
  });
};
