exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('users').then(function() {
    // Inserts seed entries
    return knex('users').insert([
      {
        name: 'David Dobbie',
        password: 'lStXXL9aE',
        email: 'ddobbie9c@psu.edu',
        phone: '464-625-7891',
        country: 'Philippines',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Kathi Robley',
        password: 'ht9707R1u',
        email: 'krobley9d@mac.com',
        phone: '238-932-4540',
        country: 'Syria',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Thekla Delgua',
        password: 'BWyTD6',
        email: 'tdelgua9e@blogtalkradio.com',
        phone: '335-998-1500',
        country: 'Argentina',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Alvira Esser',
        password: 'WsUbIv2',
        email: 'aesser9f@wikimedia.org',
        phone: '141-790-2671',
        country: 'Bolivia',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Dave Eagle',
        password: 'HDlMJvsJyuAh',
        email: 'deagle9g@zdnet.com',
        phone: '619-614-2710',
        country: 'Sri Lanka',
        org_id: 2,
        role_id: 1,
      },
      {
        name: 'Ellis Biddleston',
        password: 'bcQXZJcHO',
        email: 'ebiddleston9h@alexa.com',
        phone: '388-827-4241',
        country: 'China',
        org_id: 2,
        role_id: 1,
      },
      {
        name: 'Daffie Zoppo',
        password: 'DJs5gXlV',
        email: 'dzoppo9i@wired.com',
        phone: '794-323-9996',
        country: 'Japan',
        org_id: 2,
        role_id: 3,
      },
      {
        name: 'Web Godon',
        password: 'r0wVUkes',
        email: 'wgodon9j@stanford.edu',
        phone: '660-379-2638',
        country: 'Poland',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Hartwell Brumby',
        password: 'ikWEj9YHZ',
        email: 'hbrumby9k@devhub.com',
        phone: '529-603-9908',
        country: 'China',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Sharity Guerry',
        password: '0Fq64mX',
        email: 'sguerry9l@yelp.com',
        phone: '725-440-7701',
        country: 'Azerbaijan',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Christiana Dibbe',
        password: 'FI4nFH5atj7',
        email: 'cdibbe9m@slashdot.org',
        phone: '683-945-3440',
        country: 'Peru',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Corabelle Howick',
        password: 'zoK9aOFhVYC',
        email: 'chowick9n@businesswire.com',
        phone: '652-254-2031',
        country: 'Poland',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Arline Swannie',
        password: 'XB6QjMMR',
        email: 'aswannie9o@blogtalkradio.com',
        phone: '885-156-3269',
        country: 'China',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Maddi Curneen',
        password: 'FpY3Su',
        email: 'mcurneen9p@yellowpages.com',
        phone: '740-598-9851',
        country: 'Thailand',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Jerrilee Melhuish',
        password: '8lc5GZ2d',
        email: 'jmelhuish9q@freewebs.com',
        phone: '267-273-8134',
        country: 'United States',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Emmaline Clavey',
        password: 'eBkBxA3KAOf',
        email: 'eclavey9r@gnu.org',
        phone: '182-865-0205',
        country: 'Indonesia',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Louise Rulf',
        password: 'Km6kha5jeR',
        email: 'lrulf9s@ucoz.com',
        phone: '471-881-6601',
        country: 'Cuba',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Paulo Bussons',
        password: 'vhykIUIyXq0',
        email: 'pbussons9t@ycombinator.com',
        phone: '100-344-2097',
        country: 'Egypt',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Gustavus Hockey',
        password: 'dEdNOTe',
        email: 'ghockey9u@technorati.com',
        phone: '894-803-1835',
        country: 'Russia',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Grayce Stanyland',
        password: 'OZOWtYr',
        email: 'gstanyland9v@quantcast.com',
        phone: '130-757-8168',
        country: 'Turkmenistan',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Gav Kunert',
        password: 'zESrQZqX',
        email: 'gkunert9w@ucoz.com',
        phone: '260-327-7742',
        country: 'China',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Thornie Mariotte',
        password: 'rozzxEOfDEC',
        email: 'tmariotte9x@ft.com',
        phone: '752-709-5908',
        country: 'Sweden',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Rosabelle Chieco',
        password: 'OVDP2pSj9',
        email: 'rchieco9y@time.com',
        phone: '372-217-4642',
        country: 'South Korea',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Gauthier Kingsworth',
        password: 'YDkZlHHV5SY',
        email: 'gkingsworth9z@time.com',
        phone: '670-667-2897',
        country: 'Russia',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Allister Marre',
        password: 'fOHtCkIBL',
        email: 'amarrea0@digg.com',
        phone: '148-744-7053',
        country: 'Indonesia',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Halimeda Sperling',
        password: '7rlcWiHk',
        email: 'hsperlinga1@samsung.com',
        phone: '957-705-4642',
        country: 'Nigeria',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Sunny Rizzo',
        password: '2R1Am2mPUf',
        email: 'srizzoa2@loc.gov',
        phone: '230-604-8502',
        country: 'China',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Olav Ridges',
        password: 'gogLz8',
        email: 'oridgesa3@alibaba.com',
        phone: '437-124-2387',
        country: 'France',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Wolfie Duerdin',
        password: '1do2OxtoV0i',
        email: 'wduerdina4@mlb.com',
        phone: '858-718-3988',
        country: 'Ivory Coast',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Lissie Gorvin',
        password: '0AwW0b',
        email: 'lgorvina5@51.la',
        phone: '278-378-9222',
        country: 'Poland',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Mathe Hold',
        password: 'ZNf2LX6rHFJ',
        email: 'mholda6@loc.gov',
        phone: '321-536-3371',
        country: 'United States',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Edmund Brocklehurst',
        password: 'ACYRd1zU9',
        email: 'ebrocklehursta7@smugmug.com',
        phone: '449-126-1394',
        country: 'Poland',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Joan Knok',
        password: 'TK8Q6OjWVih',
        email: 'jknoka8@yellowbook.com',
        phone: '902-719-4068',
        country: 'Bulgaria',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Genna Marchelli',
        password: 'SeOfLhKN4olG',
        email: 'gmarchellia9@patch.com',
        phone: '727-313-6276',
        country: 'China',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Teresita Batecok',
        password: 'YKymSXSCPa',
        email: 'tbatecokaa@hibu.com',
        phone: '227-349-9803',
        country: 'China',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Elston Petrolli',
        password: 'yCNMh2z8',
        email: 'epetrolliab@wunderground.com',
        phone: '189-436-4189',
        country: 'Thailand',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Debor McNeachtain',
        password: 'Vi0psO',
        email: 'dmcneachtainac@tamu.edu',
        phone: '232-167-2423',
        country: 'Germany',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Alika Rickardsson',
        password: 'gmJVlI',
        email: 'arickardssonad@live.com',
        phone: '858-726-1185',
        country: 'China',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Alexandros Labrone',
        password: 'H7EVHJK',
        email: 'alabroneae@posterous.com',
        phone: '837-823-9321',
        country: 'Russia',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Sigismund Cashin',
        password: 'ddcLymhg',
        email: 'scashinaf@usgs.gov',
        phone: '842-893-0764',
        country: 'Indonesia',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Erin Pawnsford',
        password: 'eL4gjVupZ',
        email: 'epawnsfordag@baidu.com',
        phone: '765-855-4083',
        country: 'Colombia',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Bonita Myrkus',
        password: 'Edm6Z6SZVUfV',
        email: 'bmyrkusah@unc.edu',
        phone: '102-471-3695',
        country: 'Brazil',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Berky Gorner',
        password: '1FzSMcTNq',
        email: 'bgornerai@harvard.edu',
        phone: '855-489-7935',
        country: 'China',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Naoma Leppington',
        password: 'qUvPoKt5',
        email: 'nleppingtonaj@soup.io',
        phone: '232-886-6904',
        country: 'Greece',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Urbain Glasby',
        password: 'VoQXYJEjzyVA',
        email: 'uglasbyak@cnet.com',
        phone: '632-803-2206',
        country: 'Poland',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Shannon Francescuccio',
        password: 'IYK52fF',
        email: 'sfrancescuccioal@wunderground.com',
        phone: '914-335-8779',
        country: 'China',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Tybalt MacCallester',
        password: 'c1bsDAX',
        email: 'tmaccallesteram@canalblog.com',
        phone: '615-721-3756',
        country: 'Sweden',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Cherianne Umfrey',
        password: 'eALu1DZAmF',
        email: 'cumfreyan@tinyurl.com',
        phone: '683-131-0094',
        country: 'Indonesia',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Yorgo Iacovolo',
        password: 'y2mZ4mbG52z',
        email: 'yiacovoloao@un.org',
        phone: '559-404-4365',
        country: 'Sudan',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Marijo Conry',
        password: 'fsGSWxoX8BL',
        email: 'mconryap@wordpress.com',
        phone: '515-953-1111',
        country: 'China',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Becki Gwynn',
        password: 'ohxBISTGgZEa',
        email: 'bgwynnaq@china.com.cn',
        phone: '195-271-2534',
        country: 'China',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Rufe Heaney`',
        password: 'PvXQsesn2wsJ',
        email: 'rheaneyar@twitter.com',
        phone: '902-172-5441',
        country: 'Russia',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Odelinda Luckham',
        password: '0AwHZh2UVV',
        email: 'oluckhamas@privacy.gov.au',
        phone: '688-640-5689',
        country: 'Russia',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Jillana Ochterlony',
        password: 'lm9Lvkl1',
        email: 'jochterlonyat@nih.gov',
        phone: '115-967-0119',
        country: 'Indonesia',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Doy Allkins',
        password: '4Y4nPH3kB1hp',
        email: 'dallkinsau@blogger.com',
        phone: '638-580-0682',
        country: 'China',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Elie Witheridge',
        password: 'kr3gQ7WhRr7',
        email: 'ewitheridgeav@mysql.com',
        phone: '213-402-9979',
        country: 'Norway',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Romona Anstice',
        password: 'MjVi2FJWtzz',
        email: 'ransticeaw@angelfire.com',
        phone: '449-372-7889',
        country: 'Saudi Arabia',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Allx Heine',
        password: 'FEyVLx1XUXKD',
        email: 'aheineax@youtube.com',
        phone: '872-856-1549',
        country: 'China',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Tuckie Lafuente',
        password: 'jXm85Qj',
        email: 'tlafuenteay@bing.com',
        phone: '543-343-2637',
        country: 'Philippines',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Netty Cowoppe',
        password: 'isUhhf',
        email: 'ncowoppeaz@prlog.org',
        phone: '612-490-6555',
        country: 'Malaysia',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Araldo Ockendon',
        password: 'ZcM0Ixb7yV',
        email: 'aockendonb0@toplist.cz',
        phone: '646-127-7736',
        country: 'South Africa',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Clemente Empson',
        password: 'qmvW73bQM',
        email: 'cempsonb1@dedecms.com',
        phone: '807-611-0327',
        country: 'South Korea',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Jewell Mowbray',
        password: 'gG3QiY',
        email: 'jmowbrayb2@ucsd.edu',
        phone: '716-747-5539',
        country: 'Sudan',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Paxon Cham',
        password: 'AjKBA2kPnq',
        email: 'pchamb3@ucsd.edu',
        phone: '239-276-8995',
        country: 'Portugal',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Lora Lascell',
        password: 'r3OwiS',
        email: 'llascellb4@rakuten.co.jp',
        phone: '308-636-1489',
        country: 'Indonesia',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Gasper Andre',
        password: 'YYu84k',
        email: 'gandreb5@cocolog-nifty.com',
        phone: '270-549-3937',
        country: 'Mauritius',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Farleigh Whelpdale',
        password: 'QHROZYNBIxcV',
        email: 'fwhelpdaleb6@amazon.com',
        phone: '817-809-8106',
        country: 'China',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Gwyn Lesurf',
        password: 'vXQK5sTOz0Cf',
        email: 'glesurfb7@arizona.edu',
        phone: '213-148-2562',
        country: 'United States',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Francklin Dionis',
        password: 'qI8nEvmdF5J1',
        email: 'fdionisb8@oakley.com',
        phone: '684-974-6727',
        country: 'Kazakhstan',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Mable Albrook',
        password: 'jn6kw2a13',
        email: 'malbrookb9@craigslist.org',
        phone: '884-137-3016',
        country: 'China',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Rosemarie Densumbe',
        password: '7SzgBVB',
        email: 'rdensumbeba@noaa.gov',
        phone: '375-697-5350',
        country: 'China',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Maridel Cordle',
        password: '52SN5hbo',
        email: 'mcordlebb@networksolutions.com',
        phone: '355-925-1159',
        country: 'Poland',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Hannah Marquand',
        password: 'hNctcpL',
        email: 'hmarquandbc@cbslocal.com',
        phone: '910-183-5983',
        country: 'Mexico',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Adrea Pasterfield',
        password: 'hiX6tgm',
        email: 'apasterfieldbd@auda.org.au',
        phone: '207-798-9710',
        country: 'Peru',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Demetra Cabral',
        password: 'W5Qvu9',
        email: 'dcabralbe@biblegateway.com',
        phone: '995-501-6659',
        country: 'Mexico',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Lilla Dellar',
        password: 'iOAj6zDK',
        email: 'ldellarbf@clickbank.net',
        phone: '411-115-1346',
        country: 'France',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Saunders Vescovo',
        password: 'VLwFHGD5Tt87',
        email: 'svescovobg@squarespace.com',
        phone: '193-152-3341',
        country: 'Slovenia',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Dorothy Frangleton',
        password: 'ViCHvyGU',
        email: 'dfrangletonbh@stumbleupon.com',
        phone: '250-395-0110',
        country: 'Indonesia',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Taffy Waller-Bridge',
        password: 'WgbiAFVjn8',
        email: 'twallerbridgebi@icio.us',
        phone: '930-749-8393',
        country: 'Aland Islands',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Mollee Daish',
        password: 'wDaSD4yC',
        email: 'mdaishbj@unblog.fr',
        phone: '669-602-8061',
        country: 'China',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Vivian Bartak',
        password: 'Gb8txKktFdCY',
        email: 'vbartakbk@seesaa.net',
        phone: '305-411-3345',
        country: 'Indonesia',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Fred Minard',
        password: 'Q6DOmIx9xrl',
        email: 'fminardbl@google.ca',
        phone: '264-735-0672',
        country: 'Thailand',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Kelsi Dorant',
        password: 'bMNkAYRezc',
        email: 'kdorantbm@cnet.com',
        phone: '162-816-5943',
        country: 'Slovenia',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Dunn Dawley',
        password: 'm8qeNUFi9',
        email: 'ddawleybn@yahoo.com',
        phone: '143-699-9443',
        country: 'Colombia',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Beverlie Ridout',
        password: 'TMU7hMXkcx',
        email: 'bridoutbo@nymag.com',
        phone: '111-888-8935',
        country: 'China',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Mireille Fryatt',
        password: 'p4G87xZeDV4n',
        email: 'mfryattbp@sogou.com',
        phone: '441-936-0269',
        country: 'Russia',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Katherine Aylward',
        password: 'd5vr4vn',
        email: 'kaylwardbq@woothemes.com',
        phone: '497-941-1101',
        country: 'Portugal',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Mill Ludye',
        password: 'BwHNKEy',
        email: 'mludyebr@usatoday.com',
        phone: '741-510-4948',
        country: 'Pakistan',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Laureen Wilkie',
        password: '0qBdUHEQ',
        email: 'lwilkiebs@networksolutions.com',
        phone: '509-751-8501',
        country: 'Japan',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Pearce Madrell',
        password: 'n2oL36Q9',
        email: 'pmadrellbt@google.com.au',
        phone: '993-372-2054',
        country: 'Brazil',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Easter Lyngsted',
        password: 'KvzcJU',
        email: 'elyngstedbu@tuttocitta.it',
        phone: '951-825-1868',
        country: 'Indonesia',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Ade Mosen',
        password: 'YFODHDyj',
        email: 'amosenbv@dmoz.org',
        phone: '745-769-6703',
        country: 'China',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Debi Slatter',
        password: '94K29Q8T9id',
        email: 'dslatterbw@mashable.com',
        phone: '770-836-3011',
        country: 'Bolivia',
        org_id: 2,
        role_id: 2,
      },
      {
        name: 'Ransell Behling',
        password: 'C3joZblnV',
        email: 'rbehlingbx@unicef.org',
        phone: '756-561-8740',
        country: 'Czech Republic',
        org_id: 2,
        role_id: 2,
      },
    ]);
  });
};
